<<<<<<< before updating
formatter: "markdown"

output:
  file: "README.md"
  mode: "inject"

sort:
  enabled: false
=======
formatter: "markdown table"
>>>>>>> after updating

sections:
  hide:
    - providers
<<<<<<< before updating
=======

sort:
  enabled: false
>>>>>>> after updating
