name: Automated Approvals

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  automated-approvals:
    name: Automated Approvals
    permissions:
      pull-requests: read
      contents: read
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@088489d7b5f9ee3e0f63110b7fa5a13f7fd523e2
    secrets: inherit # pragma: allowlist secret
